/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux jacky-HP-ProDesk-600-G2-SFF 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "2018年 05月 14日 星期一 12:10:34 CST"
#define BUILD_ENV_SRCDIR "/home/RT-AC54U/asuswrt/release/src/router/samba-3.5.8/source3"
#define BUILD_ENV_BUILDDIR "/home/RT-AC54U/asuswrt/release/src/router/samba-3.5.8/source3"
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "jacky-HP-ProDesk-600-G2-SFF"
#define BUILD_ENV_COMPILER "mipsel-uclibc-gcc"
#endif /* _BUILD_ENV_H */
